/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_weiwobang_paotui_jnitools_JniTools */

#ifndef _Included_com_weiwobang_paotui_jnitools_JniTools
#define _Included_com_weiwobang_paotui_jnitools_JniTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_weiwobang_paotui_jnitools_JniTools
 * Method:    Add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_weiwobang_paotui_jnitools_JniTools_Add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
